irrd:
    database_url: 'postgresql://localhost:5432/irrd'
    access_lists:
        http_database_status:
            - '::/32'
            - '127.0.0.1'
    server:
        http:
            access_list: http_database_status
    auth:
        gnupg_keyring: /Users/sasha/dev/irrd4/gnupg/
        override_password: $1$J6KycItM$MbPaBU6iFSGFV299Rk7Di0
    email:
        footer: ""
        from: example@example.com
        smtp: localhost
    sources_default:
        - NTTCOM
#        - INTERNAL
        - RADB
        - RIPE
        - RIPE-NONAUTH
        - ALTDB
        - BELL
        - LEVEL3
        - RGNET
        - APNIC
        - JPIRR
        - ARIN
        - BBOI
        - TC
        - AFRINIC
#        - ARIN-WHOIS
#        - RPKI
#        - REGISTROBR
    sources:
        AFRINIC:
            authoritative: false
            import_serial_source: 'ftp://ftp.afrinic.net/pub/dbase/AFRINIC.CURRENTSERIAL'
            import_source: 'ftp://ftp.afrinic.net/pub/dbase/afrinic.db.gz'
            keep_journal: true
            nrtm_host: rr.ntt.net
            nrtm_port: 43
            object_class_filter:
                - as-set
                - aut-num
                - filter-set
                - inet-rtr
                - key-cert
                - mntner
                - peering-set
                - route
                - route6
                - route-set
                - rtr-set
        ALTDB:
            import_serial_source: 'ftp://ftp.radb.net/radb/dbase/ALTDB.CURRENTSERIAL'
            import_source: 'ftp://ftp.radb.net/radb/dbase/altdb.db.gz'
            keep_journal: true
            nrtm_host: rr.ntt.net
            nrtm_port: 43
        APNIC:
            authoritative: false
            import_serial_source: 'ftp://ftp.arin.net/pub/rr/ARIN.CURRENTSERIAL'
            import_source:
                - 'ftp://ftp.apnic.net/pub/apnic/whois/apnic.db.as-set.gz'
                - 'ftp://ftp.apnic.net/pub/apnic/whois/apnic.db.aut-num.gz'
                - 'ftp://ftp.apnic.net/pub/apnic/whois/apnic.db.filter-set.gz'
                - 'ftp://ftp.apnic.net/pub/apnic/whois/apnic.db.inet-rtr.gz'
                - 'ftp://ftp.apnic.net/pub/apnic/whois/apnic.db.key-cert.gz'
                - 'ftp://ftp.apnic.net/pub/apnic/whois/apnic.db.mntner.gz'
                - 'ftp://ftp.apnic.net/pub/apnic/whois/apnic.db.peering-set.gz'
                - 'ftp://ftp.apnic.net/pub/apnic/whois/apnic.db.route-set.gz'
                - 'ftp://ftp.apnic.net/pub/apnic/whois/apnic.db.route.gz'
                - 'ftp://ftp.apnic.net/pub/apnic/whois/apnic.db.route6.gz'
                - 'ftp://ftp.apnic.net/pub/apnic/whois/apnic.db.rtr-set.gz'
            keep_journal: true
            nrtm_host: rr.ntt.net
            nrtm_port: 43
            object_class_filter:
                - as-set
                - aut-num
                - filter-set
                - inet-rtr
                - key-cert
                - mntner
                - peering-set
                - route
                - route6
                - route-set
                - rtr-set
        ARIN:
            authoritative: false
            import_serial_source: 'ftp://ftp.arin.net/pub/rr/ARIN.CURRENTSERIAL'
            import_source: 'ftp://ftp.arin.net/pub/rr/arin.db'
            keep_journal: true
            nrtm_host: rr.arin.net
            nrtm_port: 4444
            object_class_filter:
                - as-set
                - aut-num
                - filter-set
                - inet-rtr
                - key-cert
                - mntner
                - peering-set
                - route
                - route6
                - route-set
                - rtr-set
        BBOI:
            authoritative: false
            import_serial_source: 'ftp://irr.bboi.net/BBOI.CURRENTSERIAL'
            import_source: 'ftp://irr.bboi.net/bboi.db.gz'
            keep_journal: true
            nrtm_host: irr.bboi.net
            nrtm_port: 43
            object_class_filter:
                - as-set
                - aut-num
                - filter-set
                - inet-rtr
                - key-cert
                - mntner
                - peering-set
                - route
                - route6
                - route-set
                - rtr-set
        BELL:
            import_serial_source: 'ftp://ftp.radb.net/radb/dbase/BELL.CURRENTSERIAL'
            import_source: 'ftp://ftp.radb.net/radb/dbase/bell.db.gz'
            keep_journal: true
            nrtm_host: rr.ntt.net
            nrtm_port: 43
            object_class_filter:
                - as-set
                - aut-num
                - filter-set
                - inet-rtr
                - key-cert
                - mntner
                - peering-set
                - route
                - route6
                - route-set
                - rtr-set
        JPIRR:
            import_serial_source: 'ftp://ftp.radb.net/radb/dbase/JPIRR.CURRENTSERIAL'
            import_source: 'ftp://ftp.radb.net/radb/dbase/jpirr.db.gz'
            keep_journal: true
            nrtm_host: rr.ntt.net
            nrtm_port: 43
            object_class_filter:
                - as-set
                - aut-num
                - filter-set
                - inet-rtr
                - key-cert
                - mntner
                - peering-set
                - route
                - route6
                - route-set
                - rtr-set
        LEVEL3:
            authoritative: false
            import_serial_source: 'ftp://rr.level3.net/pub/rr/LEVEL3.CURRENTSERIAL'
            import_source: 'ftp://rr.Level3.net/pub/rr/level3.db.gz'
            keep_journal: true
            nrtm_host: rr.level3.net
            nrtm_port: 43
            object_class_filter:
                - as-set
                - aut-num
                - filter-set
                - inet-rtr
                - key-cert
                - mntner
                - peering-set
                - route
                - route6
                - route-set
                - rtr-set
        NTTCOM:
            authoritative: true
            import_serial_source: 'ftp://rr1.ntt.net/nttcomRR/NTTCOM.CURRENTSERIAL'
            import_source: 'ftp://rr1.ntt.net/nttcomRR/nttcom.db.gz'
            keep_journal: true
            nrtm_host: rr.ntt.net
            nrtm_port: 43
        RADB:
            authoritative: false
            import_serial_source: 'ftp://ftp.radb.net/radb/dbase/RADB.CURRENTSERIAL'
            import_source: 'ftp://ftp.radb.net/radb/dbase/radb.db.gz'
            keep_journal: true
            nrtm_host: whois.radb.net
            nrtm_port: 43
            object_class_filter:
                - as-set
                - aut-num
                - filter-set
                - inet-rtr
                - key-cert
                - mntner
                - peering-set
                - route
                - route6
                - route-set
                - rtr-set
        RGNET:
            authoritative: false
            import_serial_source: 'ftp://rg.net/rgnet/RGNET.CURRENTSERIAL'
            import_source: 'ftp://rg.net/rgnet/RGNET.db.gz'
            keep_journal: true
            nrtm_host: whois.rg.net
            nrtm_port: 43
            object_class_filter:
                - as-set
                - aut-num
                - filter-set
                - inet-rtr
                - key-cert
                - mntner
                - peering-set
                - route
                - route6
                - route-set
                - rtr-set
        RIPE:
            authoritative: false
            import_serial_source: 'ftp://ftp.ripe.net/ripe/dbase/RIPE.CURRENTSERIAL'
            import_source:
                - 'ftp://ftp.ripe.net/ripe/dbase/split/ripe.db.as-set.gz'
                - 'ftp://ftp.ripe.net/ripe/dbase/split/ripe.db.aut-num.gz'
                - 'ftp://ftp.ripe.net/ripe/dbase/split/ripe.db.filter-set.gz'
                - 'ftp://ftp.ripe.net/ripe/dbase/split/ripe.db.inet-rtr.gz'
                - 'ftp://ftp.ripe.net/ripe/dbase/split/ripe.db.key-cert.gz'
                - 'ftp://ftp.ripe.net/ripe/dbase/split/ripe.db.mntner.gz'
                - 'ftp://ftp.ripe.net/ripe/dbase/split/ripe.db.peering-set.gz'
                - 'ftp://ftp.ripe.net/ripe/dbase/split/ripe.db.route.gz'
                - 'ftp://ftp.ripe.net/ripe/dbase/split/ripe.db.route6.gz'
                - 'ftp://ftp.ripe.net/ripe/dbase/split/ripe.db.route-set.gz'
                - 'ftp://ftp.ripe.net/ripe/dbase/split/ripe.db.rtr-set.gz'
            keep_journal: true
            nrtm_host: 193.0.6.135
            nrtm_port: 4444
            object_class_filter:
                - as-set
                - aut-num
                - filter-set
                - inet-rtr
                - key-cert
                - mntner
                - peering-set
                - route
                - route6
                - route-set
                - rtr-set
        RIPE-NONAUTH:
            authoritative: false
            import_serial_source: 'ftp://ftp.ripe.net/ripe/dbase/RIPE-NONAUTH.CURRENTSERIAL'
            import_source:
                - 'ftp://ftp.ripe.net/ripe/dbase/split/ripe-nonauth.db.aut-num.gz'
                - 'ftp://ftp.ripe.net/ripe/dbase/split/ripe-nonauth.db.route.gz'
                - 'ftp://ftp.ripe.net/ripe/dbase/split/ripe-nonauth.db.route6.gz'
            keep_journal: true
            nrtm_host: 193.0.6.135
            nrtm_port: 4444
            object_class_filter:
                - as-set
                - aut-num
                - filter-set
                - inet-rtr
                - key-cert
                - mntner
                - peering-set
                - route
                - route6
                - route-set
                - rtr-set
        TC:
            import_serial_source: 'ftp://ftp.radb.net/radb/dbase/TC.CURRENTSERIAL'
            import_source: 'ftp://ftp.radb.net/radb/dbase/tc.db.gz'
            keep_journal: true
            nrtm_host: rr.ntt.net
            nrtm_port: 43
