EMAIL_SEPARATOR = '\n=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=--=-\n'
EMAIL_RETURN_MSGS_COMMAND = 'TEST_RETURN_MESSAGES'
EMAIL_DISCARD_MSGS_COMMAND = 'TEST_DISCARD_MESSAGES'
EMAIL_SMTP_PORT = 2500
