# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    rust: "1.64"
  jobs:
    pre_create_environment:
      - asdf plugin add poetry
      - asdf install poetry latest
      - asdf global poetry latest
      - poetry config virtualenvs.create false
    post_install:
      - poetry install -vvv --with=docs
      - ls /home/docs/checkouts/readthedocs.org/user_builds/irrd/envs/docfix
      - ls /home/docs/checkouts/readthedocs.org/user_builds/irrd/envs/docfix/lib/python3.11/site-packages/
      - ls /home/docs/.asdf/installs/python/3.11.6/lib/python3.11/site-packages


# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py
   builder: dirhtml
