# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    rust: "1.64"
  jobs:
    post_install:
      # This is copied from the poetry config - not great but just could not get it working otherwise
      - pip install sphinx==6.1.3
      - pip install sphinxcontrib-spelling==8.0.0
      - pip install sphinx-immaterial==0.11.11
      - pip install pyenchant==3.2.2

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py
   builder: dirhtml
