services:
  irrd:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        - APP_PATH=$APP_PATH
        - CONFIG_FILE=$CONFIG_FILE
    ports:
      - "8080:8080"
      - "8043:8043"
    volumes:
      - ../:$APP_PATH/:rw
    entrypoint:
      # A custom entry point is needed to init the DB before starting IRRd
      - $APP_PATH/docker/irrd_init.sh
      - "$APP_PATH"
    environment:
      - APP_PATH=$APP_PATH
      - DATA_PATH=$DATA_PATH
    depends_on:
      - postgresql
      - redis
      - test-postgresql
    restart: always
  postgresql:
    image: postgres:15-alpine
    environment:
      PGUSER: irrd
      POSTGRES_USER: irrd
      POSTGRES_PASSWORD: irrd
    ports:
      - "5432:5432"
    volumes:
      - ../docker/psql_init.sh:/docker-entrypoint-initdb.d/psql_init.sh:rw
    # Need to change/increase these values from the defaults because they are too low when loading in data from RIRs
    command: postgres -c random_page_cost=1 -c work_mem=50000 -c shared_buffers=102400 -c max_connections=100 -c checkpoint_timeout=86400 -c max_wal_size=2147483647
    restart: always
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 0
    restart: always
  # An instance of Postgres used for pytest
  test-postgresql:
    image: postgres:15-alpine
    environment:
      PGUSER: root
      POSTGRES_DB: irrd_test
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: root
    ports:
      - "5433:5432"
    # Default is off, needed for test_object_writing_and_status_checking()
    command: postgres -c track_commit_timestamp=on
    restart: always
